// --- Auto-generated by generate_plugin.py ---
#ifndef PULSE_COLOR_EFFECT_HPP
#define PULSE_COLOR_EFFECT_HPP

#include "wallpaper-effect.hpp"
#include <GLES3/gl3.h>
#include <glm/glm.hpp>
#include <string>
#include <vector>

class PulseColorEffectEffect : public WallpaperEffect {
public:
    PulseColorEffectEffect();
    ~PulseColorEffectEffect() override;

    // --- WallpaperEffect Interface ---
    const char* get_name() const override;
    std::vector<EffectParameter> get_parameters() const override;
    void set_parameter(const std::string& name, const EffectParameterValue& value) override;

    bool initialize(uint32_t width, uint32_t height) override;
    void render(uint32_t width, uint32_t height) override;
    void cleanup() override;
    void handle_pointer_motion(double dx, double dy, bool is_touchpad) override;

private:
    GLuint program = 0;
    GLuint vao = 0;
    float time = 0.0f;

    // --- Parameter Member Variables ---
    glm::vec3 base_color = glm::vec3(0.2f, 0.2f, 0.2f);
    float pulse_speed = 1.0;
    float pulse_strength = 0.5;
    bool color_shift_mode = false;

    // --- Uniform Locations ---
    GLuint u_time = 0;
    GLuint u_resolution = 0;
    GLuint u_base_color = 0;
    GLuint u_pulse_speed = 0;
    GLuint u_pulse_strength = 0;
    GLuint u_color_shift_mode = 0;
};

#endif // PULSE_COLOR_EFFECT_HPP