// --- Auto-generated by generate_plugin.py ---
#include "pulse-color-effect.hpp"
#include "shader-utils.hpp" // Common helpers
#include <iostream>
#include <stdexcept>

PulseColorEffectEffect::PulseColorEffectEffect() = default;
PulseColorEffectEffect::~PulseColorEffectEffect() {
    cleanup();
}

const char* PulseColorEffectEffect::get_name() const {
    return "Pulse Color Effect";
}

std::vector<EffectParameter> PulseColorEffectEffect::get_parameters() const {
    return {
        {"base_color", "Базовый цвет эффекта (R,G,B)", base_color},
        {"pulse_speed", "Скорость пульсации", pulse_speed},
        {"pulse_strength", "Амплитуда цветовой пульсации", pulse_strength},
        {"color_shift_mode", "Включить цветовой сдвиг с фазой", color_shift_mode},
    };
}

void PulseColorEffectEffect::set_parameter(const std::string& name, const EffectParameterValue& value) {
    try {
        if (name == "base_color") {
            base_color = std::get<glm::vec3>(value);
        }
        else if (name == "pulse_speed") {
            pulse_speed = std::get<float>(value);
        }
        else if (name == "pulse_strength") {
            pulse_strength = std::get<float>(value);
        }
        else if (name == "color_shift_mode") {
            color_shift_mode = std::get<bool>(value);
        }
        else {
             std::cerr << "Warning: Unknown parameter '" << name << "'." << std::endl;
        }
    } catch (const std::bad_variant_access& e) {
        std::cerr << "Warning: Type mismatch for parameter '" << name << "'. " << e.what() << std::endl;
    }
}

bool PulseColorEffectEffect::initialize(uint32_t width, uint32_t height) {
    // Note: shader_utils expects shader names relative to a common shader directory
    std::string vert_src = shader_utils::load_shader_source("pulse-color-effect/pulse_vert.glsl");
    std::string frag_src = shader_utils::load_shader_source("pulse-color-effect/pulse_frag.glsl");
    if (vert_src.empty() || frag_src.empty()) return false;

    program = shader_utils::create_shader_program(vert_src, frag_src);
    if (!program) return false;
    
    // Get uniform locations
    u_time = glGetUniformLocation(program, "time");
    u_resolution = glGetUniformLocation(program, "resolution");
    u_base_color = glGetUniformLocation(program, "base_color");
    u_pulse_speed = glGetUniformLocation(program, "pulse_speed");
    u_pulse_strength = glGetUniformLocation(program, "pulse_strength");
    u_color_shift_mode = glGetUniformLocation(program, "color_shift_mode");

    // Setup VAO for a fullscreen quad/triangle
    glGenVertexArrays(1, &vao);
    glBindVertexArray(vao);
    
    std::cout << "'Pulse Color Effect' initialized." << std::endl;
    return true;
}

void PulseColorEffectEffect::render(uint32_t width, uint32_t height) {
    glUseProgram(program);
    
    time += 0.016f; // Assume ~60 FPS
    glUniform1f(u_time, time);
    glUniform2f(u_resolution, static_cast<float>(width), static_cast<float>(height));
    
    // Set parameter uniforms
    glUniform3fv(u_base_color, 1, &base_color[0]);
    glUniform1f(u_pulse_speed, pulse_speed);
    glUniform1f(u_pulse_strength, pulse_strength);
    glUniform1i(u_color_shift_mode, color_shift_mode);

    // Draw a fullscreen triangle (no VBO needed)
    glBindVertexArray(vao);
    glDrawArrays(GL_TRIANGLES, 0, 3);
    glBindVertexArray(0);
}

void PulseColorEffectEffect::cleanup() {
    if (program) glDeleteProgram(program);
    if (vao) glDeleteVertexArrays(1, &vao);
    program = 0;
    vao = 0;
}

void PulseColorEffectEffect::handle_pointer_motion(double dx, double dy, bool is_touchpad) {
    // Implement if needed by the shader
}

// --- Exported C functions for the plugin system ---
extern "C" {
    WallpaperEffect* create_effect() {
        return new PulseColorEffectEffect();
    }

    void destroy_effect(WallpaperEffect* effect) {
        delete effect;
    }
}