// --- Auto-generated by generate_plugin.py ---
#include "glowing-points-effect.hpp"
#include "shader-utils.hpp" // Common helpers
#include <iostream>
#include <stdexcept>

GlowingPointsEffectEffect::GlowingPointsEffectEffect() = default;
GlowingPointsEffectEffect::~GlowingPointsEffectEffect() {
    cleanup();
}

const char* GlowingPointsEffectEffect::get_name() const {
    return "Glowing Points Effect";
}

std::vector<EffectParameter> GlowingPointsEffectEffect::get_parameters() const {
    return {

    };
}

void GlowingPointsEffectEffect::set_parameter(const std::string& name, const EffectParameterValue& value) {
    try {

    } catch (const std::bad_variant_access& e) {
        std::cerr << "Warning: Type mismatch for parameter '" << name << "'. " << e.what() << std::endl;
    }
}

bool GlowingPointsEffectEffect::initialize(uint32_t width, uint32_t height) {
    // Note: shader_utils expects shader names relative to a common shader directory
    std::string vert_src = shader_utils::load_shader_source("glowing-points-effect/sphere_vert.glsl");
    std::string frag_src = shader_utils::load_shader_source("glowing-points-effect/sphere_frag.glsl");
    if (vert_src.empty() || frag_src.empty()) return false;

    program = shader_utils::create_shader_program(vert_src, frag_src);
    if (!program) return false;
    
    // Get uniform locations
    u_time = glGetUniformLocation(program, "time");
    u_resolution = glGetUniformLocation(program, "resolution");


    // Setup VAO for a fullscreen quad/triangle
    glGenVertexArrays(1, &vao);
    glBindVertexArray(vao);
    
    std::cout << "'Glowing Points Effect' initialized." << std::endl;
    return true;
}

void GlowingPointsEffectEffect::render(uint32_t width, uint32_t height) {
    glUseProgram(program);
    
    time += 0.016f; // Assume ~60 FPS
    glUniform1f(u_time, time);
    glUniform2f(u_resolution, static_cast<float>(width), static_cast<float>(height));
    
    // Set parameter uniforms


    // Draw a fullscreen triangle (no VBO needed)
    glBindVertexArray(vao);
    glDrawArrays(GL_TRIANGLES, 0, 3);
    glBindVertexArray(0);
}

void GlowingPointsEffectEffect::cleanup() {
    if (program) glDeleteProgram(program);
    if (vao) glDeleteVertexArrays(1, &vao);
    program = 0;
    vao = 0;
}

void GlowingPointsEffectEffect::handle_pointer_motion(double dx, double dy, bool is_touchpad) {
    // Implement if needed by the shader
}

// --- Exported C functions for the plugin system ---
extern "C" {
    WallpaperEffect* create_effect() {
        return new GlowingPointsEffectEffect();
    }

    void destroy_effect(WallpaperEffect* effect) {
        delete effect;
    }
}