// --- Auto-generated by generate_plugin.py ---
#include "glowing-points-effect.hpp"
#include "shader-utils.hpp" // Common helpers
#include <iostream>
#include <stdexcept>

GlowingPointsEffectEffect::GlowingPointsEffectEffect() = default;
GlowingPointsEffectEffect::~GlowingPointsEffectEffect() {
    cleanup();
}

const char* GlowingPointsEffectEffect::get_name() const {
    return "Glowing Points Effect";
}

std::vector<EffectParameter> GlowingPointsEffectEffect::get_parameters() const {
    return {
        {"sphere_scale", "Global scale of the sphere [cite: 28]", sphere_scale},
        {"point_size", "Base size of the glowing points", point_size},
        {"audio_bass", "Bass reactivity for point pulsing [cite: 30]", audio_bass},
        {"glow_color", "Color of the points (R,G,B)", glow_color},
    };
}

void GlowingPointsEffectEffect::set_parameter(const std::string& name, const EffectParameterValue& value) {
    try {
        if (name == "sphere_scale") {
            sphere_scale = std::get<float>(value);
        }
        else if (name == "point_size") {
            point_size = std::get<float>(value);
        }
        else if (name == "audio_bass") {
            audio_bass = std::get<float>(value);
        }
        else if (name == "glow_color") {
            glow_color = std::get<glm::vec3>(value);
        }
        else {
             std::cerr << "Warning: Unknown parameter '" << name << "'." << std::endl;
        }
    } catch (const std::bad_variant_access& e) {
        std::cerr << "Warning: Type mismatch for parameter '" << name << "'. " << e.what() << std::endl;
    }
}

bool GlowingPointsEffectEffect::initialize(uint32_t width, uint32_t height) {
    // Note: shader_utils expects shader names relative to a common shader directory
    std::string vert_src = shader_utils::load_shader_source("glowing-points-effect/sphere_vert.glsl");
    std::string frag_src = shader_utils::load_shader_source("glowing-points-effect/sphere_frag.glsl");
    if (vert_src.empty() || frag_src.empty()) return false;

    program = shader_utils::create_shader_program(vert_src, frag_src);
    if (!program) return false;
    
    // Get uniform locations
    u_time = glGetUniformLocation(program, "time");
    u_resolution = glGetUniformLocation(program, "resolution");
    u_sphere_scale = glGetUniformLocation(program, "sphere_scale");
    u_point_size = glGetUniformLocation(program, "point_size");
    u_audio_bass = glGetUniformLocation(program, "audio_bass");
    u_glow_color = glGetUniformLocation(program, "glow_color");

    // Setup VAO for a fullscreen quad/triangle
    glGenVertexArrays(1, &vao);
    glBindVertexArray(vao);
    
    std::cout << "'Glowing Points Effect' initialized." << std::endl;
    return true;
}

void GlowingPointsEffectEffect::render(uint32_t width, uint32_t height) {
    glUseProgram(program);
    
    time += 0.016f; // Assume ~60 FPS
    glUniform1f(u_time, time);
    glUniform2f(u_resolution, static_cast<float>(width), static_cast<float>(height));
    
    // Set parameter uniforms
    glUniform1f(u_sphere_scale, sphere_scale);
    glUniform1f(u_point_size, point_size);
    glUniform1f(u_audio_bass, audio_bass);
    glUniform3fv(u_glow_color, 1, &glow_color[0]);

    // Draw a fullscreen triangle (no VBO needed)
    glBindVertexArray(vao);
    glDrawArrays(GL_TRIANGLES, 0, 3);
    glBindVertexArray(0);
}

void GlowingPointsEffectEffect::cleanup() {
    if (program) glDeleteProgram(program);
    if (vao) glDeleteVertexArrays(1, &vao);
    program = 0;
    vao = 0;
}

void GlowingPointsEffectEffect::handle_pointer_motion(double dx, double dy, bool is_touchpad) {
    // Implement if needed by the shader
}

// --- Exported C functions for the plugin system ---
extern "C" {
    WallpaperEffect* create_effect() {
        return new GlowingPointsEffectEffect();
    }

    void destroy_effect(WallpaperEffect* effect) {
        delete effect;
    }
}