// --- Auto-generated by generate_plugin.py ---
#ifndef GLOWING_POINTS_EFFECT_HPP
#define GLOWING_POINTS_EFFECT_HPP

#include "wallpaper-effect.hpp"
#include <GLES3/gl3.h>
#include <glm/glm.hpp>
#include <string>
#include <vector>

class GlowingPointsEffectEffect : public WallpaperEffect {
public:
    GlowingPointsEffectEffect();
    ~GlowingPointsEffectEffect() override;

    // --- WallpaperEffect Interface ---
    const char* get_name() const override;
    std::vector<EffectParameter> get_parameters() const override;
    void set_parameter(const std::string& name, const EffectParameterValue& value) override;

    bool initialize(uint32_t width, uint32_t height) override;
    void render(uint32_t width, uint32_t height) override;
    void cleanup() override;
    void handle_pointer_motion(double dx, double dy, bool is_touchpad) override;

private:
    GLuint program = 0;
    GLuint vao = 0;
    float time = 0.0f;

    // --- Parameter Member Variables ---
    float sphere_scale = 1.0;
    float point_size = 10.0;
    float audio_bass = 0.0;
    glm::vec3 glow_color = glm::vec3(0.0f, 0.8f, 1.0f);

    // --- Uniform Locations ---
    GLuint u_time = 0;
    GLuint u_resolution = 0;
    GLuint u_sphere_scale = 0;
    GLuint u_point_size = 0;
    GLuint u_audio_bass = 0;
    GLuint u_glow_color = 0;
};

#endif // GLOWING_POINTS_EFFECT_HPP