// --- Auto-generated by generate_plugin.py ---
#include "simple-wave-effect.hpp"
#include "shader-utils.hpp" // Common helpers
#include <iostream>
#include <stdexcept>

SimpleWaveEffectEffect::SimpleWaveEffectEffect() = default;
SimpleWaveEffectEffect::~SimpleWaveEffectEffect() {
    cleanup();
}

const char* SimpleWaveEffectEffect::get_name() const {
    return "Simple Wave Effect";
}

std::vector<EffectParameter> SimpleWaveEffectEffect::get_parameters() const {
    return {
        {"wave_color", "Основной цвет волн (R,G,B)", wave_color},
        {"speed", "Скорость движения волн", speed},
        {"frequency", "Частота (количество) волн на экране", frequency},
        {"is_inverted", "Инвертировать ли цвета", is_inverted},
    };
}

void SimpleWaveEffectEffect::set_parameter(const std::string& name, const EffectParameterValue& value) {
    try {
        if (name == "wave_color") {
            wave_color = std::get<glm::vec3>(value);
        }
        else if (name == "speed") {
            speed = std::get<float>(value);
        }
        else if (name == "frequency") {
            frequency = std::get<float>(value);
        }
        else if (name == "is_inverted") {
            is_inverted = std::get<bool>(value);
        }
        else {
             std::cerr << "Warning: Unknown parameter '" << name << "'." << std::endl;
        }
    } catch (const std::bad_variant_access& e) {
        std::cerr << "Warning: Type mismatch for parameter '" << name << "'. " << e.what() << std::endl;
    }
}

bool SimpleWaveEffectEffect::initialize(uint32_t width, uint32_t height) {
    // Note: shader_utils expects shader names relative to a common shader directory
    std::string vert_src = shader_utils::load_shader_source("simple-wave-effect/wave_vert.glsl");
    std::string frag_src = shader_utils::load_shader_source("simple-wave-effect/wave_frag.glsl");
    if (vert_src.empty() || frag_src.empty()) return false;

    program = shader_utils::create_shader_program(vert_src, frag_src);
    if (!program) return false;
    
    // Get uniform locations
    u_time = glGetUniformLocation(program, "time");
    u_resolution = glGetUniformLocation(program, "resolution");
    u_wave_color = glGetUniformLocation(program, "wave_color");
    u_speed = glGetUniformLocation(program, "speed");
    u_frequency = glGetUniformLocation(program, "frequency");
    u_is_inverted = glGetUniformLocation(program, "is_inverted");

    // Setup VAO for a fullscreen quad/triangle
    glGenVertexArrays(1, &vao);
    glBindVertexArray(vao);
    
    std::cout << "'Simple Wave Effect' initialized." << std::endl;
    return true;
}

void SimpleWaveEffectEffect::render(uint32_t width, uint32_t height) {
    glUseProgram(program);
    
    time += 0.016f; // Assume ~60 FPS
    glUniform1f(u_time, time);
    glUniform2f(u_resolution, static_cast<float>(width), static_cast<float>(height));
    
    // Set parameter uniforms
    glUniform3fv(u_wave_color, 1, &wave_color[0]);
    glUniform1f(u_speed, speed);
    glUniform1f(u_frequency, frequency);
    glUniform1i(u_is_inverted, is_inverted);

    // Draw a fullscreen triangle (no VBO needed)
    glBindVertexArray(vao);
    glDrawArrays(GL_TRIANGLES, 0, 3);
    glBindVertexArray(0);
}

void SimpleWaveEffectEffect::cleanup() {
    if (program) glDeleteProgram(program);
    if (vao) glDeleteVertexArrays(1, &vao);
    program = 0;
    vao = 0;
}

void SimpleWaveEffectEffect::handle_pointer_motion(double dx, double dy, bool is_touchpad) {
    // Implement if needed by the shader
}

// --- Exported C functions for the plugin system ---
extern "C" {
    WallpaperEffect* create_effect() {
        return new SimpleWaveEffectEffect();
    }

    void destroy_effect(WallpaperEffect* effect) {
        delete effect;
    }
}