// --- Auto-generated by generate_plugin.py ---
#ifndef SIMPLE_WAVE_EFFECT_HPP
#define SIMPLE_WAVE_EFFECT_HPP

#include "wallpaper-effect.hpp"
#include <GLES3/gl3.h>
#include <glm/glm.hpp>
#include <string>
#include <vector>

class SimpleWaveEffectEffect : public WallpaperEffect {
public:
    SimpleWaveEffectEffect();
    ~SimpleWaveEffectEffect() override;

    // --- WallpaperEffect Interface ---
    const char* get_name() const override;
    std::vector<EffectParameter> get_parameters() const override;
    void set_parameter(const std::string& name, const EffectParameterValue& value) override;

    bool initialize(uint32_t width, uint32_t height) override;
    void render(uint32_t width, uint32_t height) override;
    void cleanup() override;
    void handle_pointer_motion(double dx, double dy, bool is_touchpad) override;

private:
    GLuint program = 0;
    GLuint vao = 0;
    float time = 0.0f;

    // --- Parameter Member Variables ---
    glm::vec3 wave_color = glm::vec3(0.1f, 0.5f, 1.0f);
    float speed = 2.5;
    float frequency = 20.0;
    bool is_inverted = false;

    // --- Uniform Locations ---
    GLuint u_time = 0;
    GLuint u_resolution = 0;
    GLuint u_wave_color = 0;
    GLuint u_speed = 0;
    GLuint u_frequency = 0;
    GLuint u_is_inverted = 0;
};

#endif // SIMPLE_WAVE_EFFECT_HPP